### ISSUE TITLE
Always revert to default post category on quick edit

### ISSUE THREAD

**Issue by michelesalvador** [helgatheviking/Radio-Buttons-for-Taxonomies#83] opened 2020-11-10 18:10 UTC
Hi,
I think there is an issue on Posts > Quick Edit.
In every case when click Update the category saved is always only the default post category.
The only way to choose another category on quick edit is deactivate RB4T.

**Comment by helgatheviking** [comment] 2020-11-14 17:37
Hi Michele, I can't reproduce what you are describing. Can you elaborate? Take a screen recording? 

Here's what I'm seeing: 
https://share.getcloudapp.com/WnuromrZ

Are you using the latest version from the wordpress.org plugin repo? The version here is a little bit ahead of that and hasn't been published to .org yet, but the changes so far have largely been in the script and in the bulk edit. Though there's a possibility the bulk edit issue is related to the issue you might be having in quick edit. Could you try the latest from the `master` branch and see if that resolves things for you?

**Comment by michelesalvador** [comment] 2020-11-15 08:27
I'll try to explain with screenshots.

In `Writing Settings` > `Default Post Category` there is the "Notizie" category.

![immagine](https://user-images.githubusercontent.com/7121173/99179853-99a40780-2721-11eb-9c18-2bb253f29c4a.png)

In `Posts` there is a post with another category ("Collegamenti").
I click `Quick Edit` on this post.

![immagine](https://user-images.githubusercontent.com/7121173/99180048-3b782400-2723-11eb-92f9-dddde6ef7aad.png)

I do nothing else that simply click `Update`.

![immagine](https://user-images.githubusercontent.com/7121173/99179967-82b1e500-2722-11eb-969f-9ca64e98a858.png)

Now the post has the "Notizie" category.

![immagine](https://user-images.githubusercontent.com/7121173/99180005-d15f7f00-2722-11eb-885b-637fb891bee7.png)

I'm using RB4T version 2.1.0 on WordPress 5.5.3.

![immagine](https://user-images.githubusercontent.com/7121173/99180157-2a7be280-2724-11eb-967f-920edb9ec27f.png)

**Comment by michelesalvador** [comment] 2020-11-15 09:29
I downloaded the zipped code from this repository and replaced all the files in plugins > radio-buttons-for-taxonomies.
Yes! This issue is solved: post categories are now correctly taken.

**Comment by helgatheviking** [comment] 2020-11-15 15:46
Phew! Thank you for testing that. I will try to push the changes to the .org as soon as I can.

**Comment by michelesalvador** [comment] 2020-11-16 10:10
I updated to version 2.1.1 and I confirm that this issue is fixed.

**Comment by helgatheviking** [comment] 2020-11-16 15:05
Closed by 409e342f4151b1dc35f3b624369cccb85bafacc7

**Closed by helgatheviking** 2020-11-16 15:05 UTC
