### ISSUE TITLE
Error when removing radio buttons

### ISSUE THREAD

**Issue by mciotola** [helgatheviking/Radio-Buttons-for-Taxonomies#58] opened 2019-04-28 17:11 UTC
(I have debugging on.) I tried to turn off radio buttons for a custom taxonomy, but now the following error message appears on the custom taxonomy metabox. 
 
> Warning: call_user_func() expects parameter 1 to be a valid callback, function 'show in navigation' not found or invalid function name in /home/.../wp-admin/includes/template.php on line 1306

I have not altered the cited template.

I then checked the "Completely remove options on plugin removal", but that did not work. I then tried deactivating the plug-in. I finally removed the plugin, but that did not remove the error. I can no longer see my taxonomy choices, unless I go back to radio buttons, which I no longer want.

**Comment by helgatheviking** [comment] 2019-05-04 13:23
@mciotola I cannot reproduce this. 

Is `'meta_box_cb' => 'show in navigation'` part of your `register_taxonomy()` args? `show in navigation` does not seem like a valid function name, so it makes sense to me that it would trigger an invalid/missing callback error. _Why_ that was revealed by RB4T I can't say, but I'm going to close this because I believe the issue is with your taxonomy registration.

**Closed by helgatheviking** 2019-05-04 13:23 UTC
